# https://docs.travis-ci.com/user/languages/go
language: go
go:
  - "1.15"
env:
  - GO111MODULE=on
script:
  - go vet ./...
  - go build ./...
notifications:
  email:
    on_success: change
    on_failure: change
